### ISSUE TITLE
why not using one repository with tags instead of multiple repositories

### ISSUE THREAD

**Issue by ahmedakef** [CATReloaded/CATReloaded-Circles-Roadmaps-2024#2]
hello, 
thank you for continues developing of this awesome roadmaps.

I am just curious why you choose to create a new repository each year, instead of having one repo with [version](https://git-scm.com/book/en/v2/Git-Basics-Tagging) to mark the years.

I see having one repo will be easer since you will share the link of it only once and it will always be valid

having tags will also allow the user to see the older version of the road map

**Comment by HossamMohsen7** [comment]
Hello,
Thanks for this great suggestion. we think that it's easier for viewers and maybe GitHub beginners to see different versions in different repos, but we might look into this solution next year or something.
Thank you once again!
